"""
PDF Clinical Batch Report Generator for OxyPredict.
Uses ReportLab to generate a highly professional CDSS Batch report.
"""

import datetime
from io import BytesIO
import pandas as pd

from utils.config import logger


def _import_reportlab():
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.colors import HexColor
        from reportlab.pdfgen import canvas
        from reportlab.platypus import (
            SimpleDocTemplate,
            Paragraph,
            Spacer,
            Table,
            TableStyle,
            KeepTogether,
            HRFlowable,
        )
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.graphics.shapes import Drawing
        from reportlab.graphics.charts.piecharts import Pie
        from reportlab.graphics.charts.barcharts import VerticalBarChart

        return {
            "letter": letter,
            "HexColor": HexColor,
            "canvas": canvas,
            "SimpleDocTemplate": SimpleDocTemplate,
            "Paragraph": Paragraph,
            "Spacer": Spacer,
            "Table": Table,
            "TableStyle": TableStyle,
            "KeepTogether": KeepTogether,
            "HRFlowable": HRFlowable,
            "getSampleStyleSheet": getSampleStyleSheet,
            "ParagraphStyle": ParagraphStyle,
            "Drawing": Drawing,
            "Pie": Pie,
            "VerticalBarChart": VerticalBarChart,
        }
    except Exception as e:
        logger.error("ReportLab import failed in batch_report: %s", str(e), exc_info=True)
        return None


def _require_reportlab():
    reportlab_env = _import_reportlab()
    if reportlab_env is None:
        raise ImportError(
            "ReportLab is not installed in the deployed environment. "
            "Please add 'reportlab' to requirements.txt and redeploy."
        )
    return reportlab_env


def _create_numbered_canvas(canvas_module, HexColor):
    class NumberedCanvas(canvas_module.Canvas):
        """Custom canvas that tracks pages to draw dynamic 'Page X of Y' footers."""
        def __init__(self, *args, **kwargs):
            super(NumberedCanvas, self).__init__(*args, **kwargs)
            self._saved_page_states = []

        def showPage(self):
            self._saved_page_states.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            num_pages = len(self._saved_page_states)
            for state in self._saved_page_states:
                self.__dict__.update(state)
                self.draw_page_decorations(num_pages)
                canvas_module.Canvas.showPage(self)
            canvas_module.Canvas.save(self)

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(HexColor("#64748b"))

        # Footer separator line
        self.setStrokeColor(HexColor("#e2e8f0"))
        self.setLineWidth(0.5)
        self.line(54, 45, 558, 45)  # Margins: 0.75in (54pt) from left/right

        # Footer text
        footer_text_left = "Generated by: OxyPredict Clinical Decision Support System"
        footer_text_right = f"© 2026 | Page {self._pageNumber} of {page_count}"

        self.drawString(54, 30, footer_text_left)
        self.drawRightString(558, 30, footer_text_right)
        self.restoreState()

    return NumberedCanvas


def draw_pie_chart(need_oxy, no_oxy) -> object:
    """Natively draw a Pie Chart for PDF export using ReportLab Shapes."""
    reportlab_env = _require_reportlab()
    Drawing = reportlab_env["Drawing"]
    Pie = reportlab_env["Pie"]

    d = Drawing(220, 140)
    pc = Pie()
    pc.x = 25
    pc.y = 15
    pc.width = 110
    pc.height = 110
    pc.data = [need_oxy, no_oxy]
    pc.labels = [f"Need ({need_oxy})", f"No Need ({no_oxy})"]
    pc.sideLabels = True
    
    # Slices color
    pc.slices[0].fillColor = HexColor("#ef4444")
    pc.slices[1].fillColor = HexColor("#10b981")
    
    d.add(pc)
    return d


def draw_bar_chart(low, med, high) -> object:
    """Natively draw a Bar Chart for PDF export using ReportLab Shapes."""
    reportlab_env = _require_reportlab()
    Drawing = reportlab_env["Drawing"]
    VerticalBarChart = reportlab_env["VerticalBarChart"]

    d = Drawing(220, 140)
    bc = VerticalBarChart()
    bc.x = 25
    bc.y = 15
    bc.height = 110
    bc.width = 160
    bc.data = [[low, med, high]]
    bc.categoryAxis.categoryNames = ["Low", "Medium", "High"]
    
    # Bars color mapping
    bc.bars[0, 0].fillColor = HexColor("#10b981") # Low
    bc.bars[0, 1].fillColor = HexColor("#f59e0b") # Medium
    bc.bars[0, 2].fillColor = HexColor("#ef4444") # High
    
    bc.valueAxis.valueMin = 0
    max_val = max(low, med, high)
    bc.valueAxis.valueMax = int(max_val * 1.2) if max_val > 0 else 10
    
    d.add(bc)
    return d


def generate_batch_pdf_report(
    df: pd.DataFrame,
    stats: dict,
    clinical_summary: str,
) -> bytes:
    """
    Generate a professional clinical batch prediction report PDF.

    Args:
        df: Enriched prediction results DataFrame.
        stats: Population statistical metrics.
        clinical_summary: Generated narrative summary text.

    Returns:
        bytes: Raw PDF bytes.
    """
    reportlab_env = _require_reportlab()
    letter = reportlab_env["letter"]
    HexColor = reportlab_env["HexColor"]
    SimpleDocTemplate = reportlab_env["SimpleDocTemplate"]
    getSampleStyleSheet = reportlab_env["getSampleStyleSheet"]
    ParagraphStyle = reportlab_env["ParagraphStyle"]
    Paragraph = reportlab_env["Paragraph"]
    Spacer = reportlab_env["Spacer"]
    Table = reportlab_env["Table"]
    TableStyle = reportlab_env["TableStyle"]
    KeepTogether = reportlab_env["KeepTogether"]
    HRFlowable = reportlab_env["HRFlowable"]

    buffer = BytesIO()

    # Document setup (0.75-inch margins, leave 1.0-inch at bottom for footer)
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=72,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    style_title = ParagraphStyle(
        "ReportTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=HexColor("#0a2e52"),
    )
    style_subtitle = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=13,
        textColor=HexColor("#64748b"),
        textTransform="uppercase",
    )
    style_section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=15,
        textColor=HexColor("#0a2e52"),
        spaceBefore=12,
        spaceAfter=6,
        keepWithNext=True,
    )
    style_body = ParagraphStyle(
        "ReportBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=14,
        textColor=HexColor("#334155"),
    )
    style_body_bold = ParagraphStyle(
        "ReportBodyBold",
        parent=style_body,
        fontName="Helvetica-Bold",
    )
    style_table_header = ParagraphStyle(
        "TableHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=11,
        textColor=HexColor("#475569"),
        textTransform="uppercase",
    )

    story = []

    # ─────────────────────────────────────────────────────────────────────────
    # HEADER SECTION
    # ─────────────────────────────────────────────────────────────────────────
    now = datetime.datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M:%S")

    header_left = [
        Paragraph("🫁 OxyPredict", style_title),
        Paragraph("Sistem Dukungan Keputusan Klinis", style_subtitle),
        Spacer(1, 2),
        Paragraph("Laporan Klinis Massal", ParagraphStyle("HeaderBCR", parent=style_body_bold, textColor=HexColor("#1e40af"))),
    ]

    header_right = [
        Paragraph(f"<b>Date:</b> {date_str}", style_body),
        Paragraph(f"<b>Time:</b> {time_str}", style_body),
    ]

    header_table = Table(
        [[header_left, header_right]],
        colWidths=[300, 204],
    )
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
    ]))

    story.append(header_table)
    story.append(HRFlowable(width="100%", thickness=1, color=HexColor("#cbd5e1"), spaceBefore=5, spaceAfter=10))

    # ─────────────────────────────────────────────────────────────────────────
    # DATASET SUMMARY TABLE
    # ─────────────────────────────────────────────────────────────────────────
    summary_rows = [
        [
            Paragraph("<b>Total Pasien</b>", style_body),
            Paragraph(str(stats["total_patients"]), style_body_bold),
            Paragraph("<b>Pasien Risiko Rendah</b>", style_body),
            Paragraph(str(stats["low_risk"]), style_body_bold),
        ],
        [
            Paragraph("<b>Butuh Oksigen</b>", style_body),
            Paragraph(f"<font color='#dc2626'><b>{stats['need_oxy']} ({stats['need_oxy_pct']:.1f}%)</b></font>", style_body),
            Paragraph("<b>Pasien Risiko Sedang</b>", style_body),
            Paragraph(str(stats["med_risk"]), style_body_bold),
        ],
        [
            Paragraph("<b>Tidak Butuh Oksigen</b>", style_body),
            Paragraph(f"<font color='#16a34a'><b>{stats['no_oxy']}</b></font>", style_body),
            Paragraph("<b>Pasien Risiko Tinggi</b>", style_body),
            Paragraph(f"<font color='#dc2626'><b>{stats['high_risk']}</b></font>", style_body),
        ],
        [
            Paragraph("<b>Rata-rata Probabilitas</b>", style_body),
            Paragraph(f"<b>{stats['avg_probability']:.1f}%</b>", style_body_bold),
            "", ""
        ]
    ]

    summary_table = Table(summary_rows, colWidths=[130, 122, 130, 122])
    summary_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#cbd5e1")),
        ("BACKGROUND", (0, 0), (-1, -1), HexColor("#ffffff")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [HexColor("#ffffff"), HexColor("#f8fafc")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("SPAN", (2, 3), (3, 3)),
    ]))

    story.append(Paragraph("📊 Ringkasan Data & Prediksi", style_section_heading))
    story.append(summary_table)
    story.append(Spacer(1, 10))

    # ─────────────────────────────────────────────────────────────────────────
    # CLINICAL INTERPRETATION
    # ─────────────────────────────────────────────────────────────────────────
    summary_box_content = [
        [Paragraph(clinical_summary, style_body)]
    ]
    summary_box = Table(summary_box_content, colWidths=[504])
    summary_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), HexColor("#ffffff")),
        ("BOX", (0, 0), (-1, -1), 1, HexColor("#e2e8f0")),
        ("LINELEFT", (0, 0), (-1, -1), 5, HexColor("#1e40af")),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
    ]))

    story.append(Paragraph("🩺 Interpretasi Klinis", style_section_heading))
    story.append(summary_box)
    story.append(Spacer(1, 10))

    # ─────────────────────────────────────────────────────────────────────────
    # TOP 10 HIGH RISK PATIENTS TABLE
    # ─────────────────────────────────────────────────────────────────────────
    # Sort dataset by Probability descending
    sorted_df = df.sort_values(by="Probability", ascending=False)
    top_10 = sorted_df.head(10)

    top_patients_rows = [[
        Paragraph("Patient ID", style_table_header),
        Paragraph("Risk (Prob)", style_table_header),
        Paragraph("Prioritas", style_table_header),
        Paragraph("Primary Recommendation Action", style_table_header)
    ]]

    for i, (_, row) in enumerate(top_10.iterrows()):
        patient_id = row.get("Patient ID", f"Patient #{row.name + 1}")
        prob = row["Probability"]
        risk = row["Risk Level"]
        priority = row.get("Priority", "Rendah")
        rec_action = row.get("Recommendation", "N/A")
        
        # Format primary action (take first bullet point)
        first_action = rec_action.split(";")[0] if rec_action != "N/A" else "N/A"
        
        # Color code priority
        if priority in ["Darurat", "Emergency", "Tinggi"]:
            prio_color = "#dc2626"
        elif priority == "Sedang":
            prio_color = "#ca8a04"
        else:
            prio_color = "#16a34a"

        top_patients_rows.append([
            Paragraph(str(patient_id), style_body),
            Paragraph(f"{risk} ({prob:.1f}%)", style_body),
            Paragraph(f"<font color='{prio_color}'><b>{priority}</b></font>", style_body),
            Paragraph(str(first_action), style_body)
        ])

    top_table = Table(top_patients_rows, colWidths=[100, 100, 84, 220])
    top_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#f1f5f9")),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#ffffff"), HexColor("#f8fafc")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))

    story.append(Paragraph("📋 10 Pasien Risiko Tinggi Teratas", style_section_heading))
    story.append(top_table)
    story.append(Spacer(1, 10))

    # ─────────────────────────────────────────────────────────────────────────
    # POPULATION CHARTS (SIDE BY SIDE TABLE)
    # ─────────────────────────────────────────────────────────────────────────
    pie_drawing = draw_pie_chart(stats["need_oxy"], stats["no_oxy"])
    bar_drawing = draw_bar_chart(stats["low_risk"], stats["med_risk"], stats["high_risk"])

    charts_row = [
        [Paragraph("<b>Distribusi Pasien Butuh O₂ vs Tidak Butuh O₂</b>", style_subtitle), Paragraph("<b>Distribusi Kategori Risiko</b>", style_subtitle)],
        [pie_drawing, bar_drawing]
    ]
    charts_table = Table(charts_row, colWidths=[252, 252])
    charts_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ]))

    charts_section = [
        Paragraph("📈 Population Charts", style_section_heading),
        charts_table,
        Spacer(1, 10)
    ]

    # ─────────────────────────────────────────────────────────────────────────
    # DISCLAIMER
    # ─────────────────────────────────────────────────────────────────────────
    disclaimer_text = (
        "<b>Catatan Rekomendasi Klinis:</b><br/>"
        "Rekomendasi klinis disusun menggunakan aturan keputusan yang ditetapkan berdasarkan hasil prediksi model dan karakteristik pasien. "
        "Rekomendasi ini dimaksudkan untuk mendukung tenaga kesehatan dan tidak menggantikan penilaian dokter, protokol rumah sakit, atau pemeriksaan klinis."
    )
    disclaimer_box = Table([[Paragraph(disclaimer_text, style_body)]], colWidths=[504])
    disclaimer_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), HexColor("#fefbeb")),
        ("BOX", (0, 0), (-1, -1), 1, HexColor("#fef08a")),
        ("LINELEFT", (0, 0), (-1, -1), 4, HexColor("#eab308")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
    ]))
    
    charts_section.append(disclaimer_box)
    story.append(KeepTogether(charts_section))

    # Build document
    doc.build(story, canvasmaker=NumberedCanvas)

    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
